### ISSUE TITLE
Serilog's own UseSerilogRequestLogging vs TrackPerformanceFilter

### ISSUE THREAD

**Issue by abhith** [dahlsailrunner/simple-serilog#2]
By adding **UseSerilogRequestLogging** middleware, we get an almost similar log result of TrackPerformanceFilter. In the case of normal text result, the log looks like,
```
2020-03-22 15:40:58.077 +04:00 [INF] HTTP POST /v1/orders/JP5V55OG9IGK1SU4M/some-path responded 200 in 67.9459 ms
```
So in this case, do we need TrackPerformanceFilter?

It will be very helpful if we can include "UseSerilogRequestLogging" usage as part of this solution.

**Comment by dahlsailrunner** [comment]
You can absolutely use the UseSerilogRequestLogging. -- totally fine..  Sorry for late reply - I missed the notification.  Feel free to make a PR if you like to add the change!  :)
