### ISSUE TITLE
Project doesn't build under VS 16.8 (preview)

### ISSUE THREAD

**Issue by justSteve** [dahlsailrunner/simple-serilog#3]
I'm hoping to bring this project up-to-date for .net 50 but Startup.cs is blocked by: 

**The type or namespace name 'IdentityModel' does not exist in the namespace 'System' (are you missing an assembly reference?)**

**Comment by dahlsailrunner** [comment]
I'll try to look at this later today or over the weekend

-Erik Dahl
m: 651-592-4113
________________________________

**Comment by dahlsailrunner** [comment]
This was all the way back to .net core 2.2, so I'm taking some time to upgrade this with what I think are simpler and more correct ways to include all of the demo'd functionality.  I'm making good progress and the road ahead seems clear.  I'll close this issue when it's complete but it will be another couple of days I'm thinking.

If you're curious, the new `csproj` file for the UI is simply this:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IdentityModel.AspNetCore" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Simple.Serilog\Simple.Serilog.csproj" />
  </ItemGroup>

</Project>
```
I'm working my way through the projects and will keep you updated.

**Comment by dahlsailrunner** [comment]
I've updated the `baseline` folder to use .NET 5.0 and the better techniques for various things -- serilog request logging, updated oidc information with demo identity server, and better accesstoken / httpclient handling, along with system.text.json and system.net.http.json for api / json handling.

I'll be updating the other folders soon (maybe this weekend), and will update readme with information at that time as well.

**Comment by dahlsailrunner** [comment]
I've completed the updates and now it uses .NET 5.0 and some of what I consider to be good practices for token handling, api calls, logging with serilog request logging, and more.  The same code should work on .net core 3.x projects as well.  I'm going to close this issue but please let me know if you have questions.
