### ISSUE TITLE
Log.Debug("Got into Values - GET"); where is it logged

### ISSUE THREAD

**Issue by eliassal** [dahlsailrunner/simple-serilog#4]
Hi Erik,
Nice work. 1 year back I had a subscription on pluralsight and watched almost all your courses, can I communicate through this site when I have an issue? Thanks

**Comment by dahlsailrunner** [comment]
Check out the code here: https://github.com/dahlsailrunner/simple-serilog/blob/master/baseline/Simple.Serilog/SerilogHelpers.cs

Should be written to your C:\Temp directory based on this line if you're using the main branch:
```csharp
.WriteTo.File(new CompactJsonFormatter(),
                    $@"C:\temp\Logs\{applicationName}.json");
```

**Comment by eliassal** [comment]
so many thanks
